# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# REMOVE OR COMMENT OUT THIS BLOCK IF YOUR FRONTEND CALLS `/.netlify/functions/generate-itinerary` DIRECTLY
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Functions configuration
[functions]
  node_bundler = "esbuild"
  # Optional: If you have large dependencies, list them here to be external
  # external_node_modules = ["@google/generative-ai"] 
  # This setting is usually for TypeScript functions, if you're using .mjs, it's not strictly needed
  # included_files = ["netlify/functions/**/*.ts"]
